import java.util.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CalculateSalary extends javax.swing.JFrame {

    /**
     * Creates new form Payrolls
     */
    public CalculateSalary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtGrosspay = new javax.swing.JTextField();
        txtOvertime = new javax.swing.JTextField();
        txtHoliday = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Button = new javax.swing.JButton();
        txtNetpay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculate Salary");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Employee ID         :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GrossPay/month    :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Overtime/Hour      :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 160, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Holiday                :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Calculate Salary");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 240, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 80, 30));

        txtGrosspay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrosspayActionPerformed(evt);
            }
        });
        getContentPane().add(txtGrosspay, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 80, 30));

        txtOvertime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOvertimeActionPerformed(evt);
            }
        });
        getContentPane().add(txtOvertime, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 80, 30));

        txtHoliday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHolidayActionPerformed(evt);
            }
        });
        getContentPane().add(txtHoliday, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 80, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NetPay/Month       :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, 30));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, -1, -1));

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, -1, -1));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        Button.setText("Calculate");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        txtNetpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetpayActionPerformed(evt);
            }
        });
        getContentPane().add(txtNetpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 810, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtHolidayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHolidayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHolidayActionPerformed

    private void txtGrosspayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrosspayActionPerformed
        
    }//GEN-LAST:event_txtGrosspayActionPerformed

    private void txtOvertimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOvertimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOvertimeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtGrosspay.setText("");
        txtOvertime.setText("");
        txtNetpay.setText("");
        txtHoliday.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtNetpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetpayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetpayActionPerformed

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        double gross, result, s1 = 0;
        int holiday, overT;
        String s2;
        
        gross = Double.parseDouble(txtGrosspay.getText());
        holiday = Integer.parseInt(txtHoliday.getText());
        overT = Integer.parseInt(txtOvertime.getText());
        
        if (holiday > 3) {
            s1 = (holiday - 3) * 10;
            
        } else {
            s1 = 0;
        }
        
        result = (gross - s1) + (overT * 4);
        
        txtNetpay.setText(String.valueOf(result));
        
    }//GEN-LAST:event_ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Choose pilih = new Choose();
        pilih.setVisible(true);
        hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         PrintWriter output = null;
        File out;
        
        try {
            out = new File("Receipt.txt");
            output = new PrintWriter(out);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CalculateSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        output.println("--------------------------------------------------------------------");
        output.println("---------------------------Salary Receipt---------------------------");
        output.println("--------------------------------------------------------------------");
        
        
        output.println();output.println();
        
        output.println("----------------------------Informations----------------------------");
        output.println("Employee ID         : \t\t " + txtID.getText());
        output.println("Gross Payment/Month : \t\t RM" + txtGrosspay.getText());
        output.println("Overtime (Hours)    : \t\t " + txtOvertime.getText() + " hours");
        output.println("Holidays            : \t\t " + txtHoliday.getText() + " days");
        output.println("--------------------------------------------------------------------");
        
        output.println();output.println();
        
        output.println("----------------------------Calculations----------------------------");
        output.println("Gross Payment/Month : \t\t RM" + txtGrosspay.getText());
        output.println("Overtime Payment    : \t\t " + txtOvertime.getText() + " X RM2/hour");
        output.println("Holidays            : \t\t (" + txtHoliday.getText() + " days - 3 days) X RM20/day");
        output.println("--------------------------------------------------------------------");
        output.println("Net Pay = (Gross Payment + Overtime Payment) - Holidays");
        output.println("Net Pay for the month : RM" + txtNetpay.getText());
        output.println("--------------------------------------------------------------------");
        
        output.println();output.println();
        
                
        output.close();
        
        Display d = new Display();
        d.setVisible(true);
        hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtGrosspay;
    private javax.swing.JTextField txtHoliday;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNetpay;
    private javax.swing.JTextField txtOvertime;
    // End of variables declaration//GEN-END:variables
}
