
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
public class Choose extends javax.swing.JFrame {

    /**
     * Creates new form Information
     */
    public Choose() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butPayroll = new javax.swing.JButton();
        butSearch = new javax.swing.JButton();
        NoEmp = new javax.swing.JButton();
        butHire = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose Option");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butPayroll.setText("Calculate Salary");
        butPayroll.setToolTipText("");
        butPayroll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPayrollActionPerformed(evt);
            }
        });
        getContentPane().add(butPayroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 149, 51));

        butSearch.setText("Search Employee");
        butSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSearchActionPerformed(evt);
            }
        });
        getContentPane().add(butSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 150, 51));

        NoEmp.setText("Number of Employee");
        NoEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoEmpActionPerformed(evt);
            }
        });
        getContentPane().add(NoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 150, 51));

        butHire.setText("Hire Employee");
        butHire.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butHire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHireActionPerformed(evt);
            }
        });
        getContentPane().add(butHire, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 150, 51));

        jButton1.setText("Back");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose Your Option");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 400, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(838, 500));
        jLabel3.setMinimumSize(new java.awt.Dimension(838, 500));
        jLabel3.setPreferredSize(new java.awt.Dimension(838, 500));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPayrollActionPerformed
        CalculateSalary j = new CalculateSalary();
        j.setVisible(true);
        hide();
    }//GEN-LAST:event_butPayrollActionPerformed

    private void butSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSearchActionPerformed
        
        Search s = new Search();
        s.setVisible(true);
        hide();
        
        
    }//GEN-LAST:event_butSearchActionPerformed

    private void butHireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHireActionPerformed
        
        try {
            HireEmp h = new HireEmp();
            h.setVisible(true);
            hide();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Choose.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_butHireActionPerformed

    private void NoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoEmpActionPerformed
        
        
        BufferedReader in = null;
        int count = 0;
        try {
            in = new BufferedReader(new FileReader("info.txt"));
            

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String input;
        
        try {
            while ((input = in.readLine()) != null) {
                count++;
            }
        } catch (IOException ex) {
            Logger.getLogger(Choose.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            in.close();
        } catch (IOException ex) {
            Logger.getLogger(Choose.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(count >= 10)
        {   
        JOptionPane.showMessageDialog (null, "You have " + count + " employees." + "\nLatest Employee : E" + count);
        }
        else
        {
        JOptionPane.showMessageDialog (null, "You have " + count + " employees." + "\nLatest Employee : E0" + count);
        }
    }//GEN-LAST:event_NoEmpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login masuk = new Login();
        masuk.setVisible(true);
        hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NoEmp;
    private javax.swing.JButton butHire;
    private javax.swing.JButton butPayroll;
    private javax.swing.JButton butSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
